spring:
  application:
    name: hello-world
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lab_db
    username: postgres
    password: admin   # 请替换为你的实际密码

# MyBatis-Plus 配置（可选）
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰转换，例如 user_name -> userName
  global-config:
    db-config:
      id-type: auto   # 主键自增策略